#!/bin/sh -eu
REMOTE=$1
REF="${2:-master}"
PROJECT=$(basename "$REMOTE")
PACKAGE="${PROJECT%.*}" # drop .el extensions
PREFIX="site-lisp/$PACKAGE"

if [ -n "$(git status --porcelain)" ]; then
  echo "Uncommitted changes. Please run from a clean workspace."
  exit 1
fi

if [ -d "$PREFIX" ]; then
  echo "Subtree $PREFIX already exists!" 1>&2
  exit 1
fi

echo "Registering subtree at $PREFIX" 1>&2
MSG="[$PACKAGE] Initial import"
git subtree add --prefix "$PREFIX" "$REMOTE" --squash master --message "$MSG"
echo "$PREFIX $REMOTE" >> SUBTREES
git add SUBTREES
git commit -m "[$PACKAGE] Register subtree"
