language: emacs-lisp
sudo: false

env:
 - EVM_EMACS=emacs-25.3-travis
 - EVM_EMACS=emacs-26.2-travis
 - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask

install:
  - cask install

script:
  - emacs --version
  - cask exec ert-runner
  - cask build
  - cask package
